{
  "formatVersion": "1.1",
  "component": {
    "group": "com.a.asm",
    "module": "plugin",
    "version": "2.0.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-2.0.0-alpha02.jar",
          "url": "plugin-2.0.0-alpha02.jar",
          "size": 104088,
          "sha512": "f4c5803229c5d378fbd2268a845be954c3d8af04786fa73151d30987c869de32b0789616975e348b78d30e191124825316cde775a61357d26f30cded2821e325",
          "sha256": "f86e30608ece28a5532f66abaf8d7eb3120a7993bfa3daf4ee280eab58d3beae",
          "sha1": "19d8e3fb7b6a1834a270d8d725ba179b6324efd3",
          "md5": "4d5c964beb2e27b9e0d859ea33314d7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-2.0.0-alpha02.jar",
          "url": "plugin-2.0.0-alpha02.jar",
          "size": 104088,
          "sha512": "f4c5803229c5d378fbd2268a845be954c3d8af04786fa73151d30987c869de32b0789616975e348b78d30e191124825316cde775a61357d26f30cded2821e325",
          "sha256": "f86e30608ece28a5532f66abaf8d7eb3120a7993bfa3daf4ee280eab58d3beae",
          "sha1": "19d8e3fb7b6a1834a270d8d725ba179b6324efd3",
          "md5": "4d5c964beb2e27b9e0d859ea33314d7f"
        }
      ]
    }
  ]
}
