{
  "formatVersion": "1.1",
  "component": {
    "group": "com.webuy",
    "module": "plugin",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.4.jar",
          "url": "plugin-1.0.4.jar",
          "size": 43473,
          "sha512": "8660f9b01c189d3765de4e6c355dd69cfcf032753506b8eb094b5cbe7a9ba6553f1ddb31d1092f68b5bb5e2698b06218bbb5962a63e390ea41476583224f254c",
          "sha256": "b797e3daea1235dc580b06721c5a6d88e36d965857d492eeda1968bdbb9db78d",
          "sha1": "7060f28e0e6efe07dfd5d65cdcc3456deee03cbf",
          "md5": "7f61491c6bf37b34b8e188bed3fa05c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.4.jar",
          "url": "plugin-1.0.4.jar",
          "size": 43473,
          "sha512": "8660f9b01c189d3765de4e6c355dd69cfcf032753506b8eb094b5cbe7a9ba6553f1ddb31d1092f68b5bb5e2698b06218bbb5962a63e390ea41476583224f254c",
          "sha256": "b797e3daea1235dc580b06721c5a6d88e36d965857d492eeda1968bdbb9db78d",
          "sha1": "7060f28e0e6efe07dfd5d65cdcc3456deee03cbf",
          "md5": "7f61491c6bf37b34b8e188bed3fa05c3"
        }
      ]
    }
  ]
}
