{
  "formatVersion": "1.1",
  "component": {
    "group": "com.a.asm",
    "module": "plugin",
    "version": "2.0.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-2.0.0-alpha03.jar",
          "url": "plugin-2.0.0-alpha03.jar",
          "size": 104052,
          "sha512": "9ec8f40f00db0a04df6781c7cc76d22ca4e6e03d41e1d5025407c17baa49a44d8be38779d35863b6b02552d1fe10f7663058c31232a995b799a1be710076f422",
          "sha256": "dc43457df86600353e6db721e954a84f98888c340ce8ccbaeaae59251e2a0bf2",
          "sha1": "f4acf7daed5ec13750e005b823fdbe47d77d49ec",
          "md5": "423dc56d7b17dcdf1c662e5102ecbd71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-2.0.0-alpha03.jar",
          "url": "plugin-2.0.0-alpha03.jar",
          "size": 104052,
          "sha512": "9ec8f40f00db0a04df6781c7cc76d22ca4e6e03d41e1d5025407c17baa49a44d8be38779d35863b6b02552d1fe10f7663058c31232a995b799a1be710076f422",
          "sha256": "dc43457df86600353e6db721e954a84f98888c340ce8ccbaeaae59251e2a0bf2",
          "sha1": "f4acf7daed5ec13750e005b823fdbe47d77d49ec",
          "md5": "423dc56d7b17dcdf1c662e5102ecbd71"
        }
      ]
    }
  ]
}
