{
  "formatVersion": "1.1",
  "component": {
    "group": "com.webuy.asm",
    "module": "plugin",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-0.0.1.jar",
          "url": "plugin-0.0.1.jar",
          "size": 59408,
          "sha512": "20651c864ac2b33fb5e665846448c47412074d3f2591f0e87088427120325b74cedd0f1ff22c8e790800bb281f2bbb0d7b9f2844490b8dc7db1ee29df6667d33",
          "sha256": "31b1c0126b6b5aca9b1e8806a643c72a583f3262ff9a06469c59b6fbd03af83f",
          "sha1": "7603aef9243f2f5bac1647cfb7791f694fe701bf",
          "md5": "a186883c7ecaed1475b294a0d1fbd8d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-0.0.1.jar",
          "url": "plugin-0.0.1.jar",
          "size": 59408,
          "sha512": "20651c864ac2b33fb5e665846448c47412074d3f2591f0e87088427120325b74cedd0f1ff22c8e790800bb281f2bbb0d7b9f2844490b8dc7db1ee29df6667d33",
          "sha256": "31b1c0126b6b5aca9b1e8806a643c72a583f3262ff9a06469c59b6fbd03af83f",
          "sha1": "7603aef9243f2f5bac1647cfb7791f694fe701bf",
          "md5": "a186883c7ecaed1475b294a0d1fbd8d5"
        }
      ]
    }
  ]
}
